services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    container_name: keycloak-smeup-local
    command:
      - start-dev
      - --http-port=8080
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./smeup/prod:/opt/keycloak/themes/prod:ro
      - ./smeup/lab:/opt/keycloak/themes/lab:ro
      - ./smeup/lab-u-p:/opt/keycloak/themes/lab-u-p:ro
      - ./customers/università-udine/usr-psw-box:/opt/keycloak/themes/uni-u-p:ro
      - ./customers/università-udine/social-login-only:/opt/keycloak/themes/uni-social:ro
      - ./smeup/prod-v2:/opt/keycloak/themes/prod-v2:ro
      - ./smeup/prod-u-p:/opt/keycloak/themes/prod-u-p:ro
      - ./smeup/lab-v2:/opt/keycloak/themes/lab-v2:ro