# Keycloak v2 theme — Account Console (università-udine)
parent=keycloak.v3
import=common/keycloak
darkMode=true

# Logo in alto a sinistra (path relativo a resources/public)
logo=/public/logo.png
logoUrl=https://www.uniud.it/it

# Favicon
favIcon=/public/favicon.ico
favIconType=image/x-icon
