# Keycloak v2 theme — Account Console (smeup-lab)
parent=keycloak.v3
import=common/keycloak
darkMode=true
styles=css/quick-start.css css/styles.css

# Logo in alto a sinistra (path relativo a resources/public)
logo=/public/logo.png
logoUrl=https://www.smeup.com

# Favicon
favIcon=/public/favicon.ico
favIconType=image/x-icon
